
get http://localhost:8080/

###
get http://localhost:8080/api/words

###
get http://localhost:8080/api/words/3


###
delete http://localhost:8080/api/words/5

###
post http://localhost:8080/api/words/
content-type: application/json

{ "english": "owl", "finnish": "pöllö" }

###
put http://localhost:8080/api/words/2
Content-Type: application/json

{
    "english": "dogg",
    "finnish": "koira"
}

